### ISSUE TITLE
writeDataFailed,port==null

### ISSUE THREAD

**Issue by sadaharukun** [zhouzhuo810/OkUSB#2]
编译到项目中之后，发送数据之后直接port==null异常

**Comment by zhouzhuo810** [comment]
这个项目好久没维护了，我现在也没硬件，没法给你测试~

**Comment by sadaharukun** [comment]
先打开app，然后在插入usb是没有问题的。如果打开app之前就插入usb，会出现上述的异常。 感谢你的项目，帮了很大的忙

周卓 <notifications@github.com> 于2018年7月12日周四 下午4:27写道：

**Comment by zhouzhuo810** [comment]
嗯  因为监听的usb插拔，没有插拔就没初始化。 哈哈，能帮上忙最好了
